#ifndef wallet_mobile_ffi_h
#define wallet_mobile_ffi_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct AuthenticatedKVLookup AuthenticatedKVLookup;

char *ffi_build_id(void);

char *ffi_random_asset_type(void);

char *ffi_asset_type_from_value(const char *code);

bool ffi_verify_authenticated_txn(const char *state_commitment, const char *authenticated_txn);

struct AuthenticatedKVLookup *ffi_authenticated_kv_lookup_new(void);

void ffi_authenticated_kv_lookup_destroy(struct AuthenticatedKVLookup *data);

bool ffi_verify_authenticated_custom_data_result(const char *state_commitment,
                                                 const struct AuthenticatedKVLookup *authenticated_res);

#endif /* wallet_mobile_ffi_h */
