[package]
name = "fp-core"
version = "0.1.0"
authors = ["Findora <admin@findora.org>"]
edition = "2018"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora Primitive core types"
readme = "README.md"

[dependencies]
impl-trait-for-tuples = "0.2"
parking_lot = "0.11.1"
primitive-types = { version = "0.9.0", features = ["rlp", "byteorder", "serde"] }
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = { version = "1.0.124", features = ["derive"] }
storage = { git = "ssh://git@github.com/FindoraNetwork/storage.git", branch = "develop" }
tm-protos = { git = "ssh://git@github.com/FindoraNetwork/tendermint-sys.git", branch = "findora-0.33.6" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.4" }

# primitives
fp-types = { path = "../types" }
